AWSTemplateFormatVersion: 2010-09-09
Description: "This stack will deploys an ASG in internal subnets deployed as a Service Catalog product"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "ASG Internal Parameters"
        Parameters:
          - NodeName
          - EBSSize
          - EBSType
          - EBSIOPS
          - InstanceProfileName
          - InstanceType
          - SecurityGroups
          - OsType
          - DesiredCapacity
          - InstanceCountMin
          - InstanceCountMax
          - LBTargetGroupArn
      - Label:
          default: "Blueprint App Parameters"
        Parameters:
          - SecurityZone
          - DataClassification
          - ConfigureStoreBucket
          - UserdataS3script
          - BluePrintTag
          - AppSoe
          - AppPort
          - AppSecret
          - LatestWindowsAmiId
          - LatestLinuxAmiId
          - SnsTopicArn
      - Label:
          default: "Custom Tag"
        Parameters:
          - CustomTag1Name
          - CustomTag1Value
          - CustomTag2Name
          - CustomTag2Value
          - CustomTag3Name
          - CustomTag3Value
          - CustomTag4Name
          - CustomTag4Value
          - CustomTag5Name
          - CustomTag5Value
          - CustomTag6Name
          - CustomTag6Value
          - CustomTag7Name
          - CustomTag7Value
          - CustomTag8Name
          - CustomTag8Value
          - CustomTag9Name
          - CustomTag9Value
          - CustomTag10Name
          - CustomTag10Value

    # parameter labels 
    ParameterLabels:
      SecurityZone:
        default: "Security Zone"
      DataClassification:
        default: "Data Classification"
      NodeName:
        default: "Node Name"
      SecurityGroups:
        default: "Security Groups"
      OsType:
        default: "OS Type"
      AppSoe:
        default: "Application SOE AMI Id"
      UserdataS3script:
        default: "User data script from S3 bucket"
      LatestWindowsAmiId:
        default: "Latest Windows AMI Id"
      LatestLinuxAmiId:
        default: "Latest Linux AMI Id"
      AppPort:
        default: "Application Port"
      AppSecret:
        default: "Application Secret"
      ConfigureStoreBucket:
        default: "Existing ConfigureStore S3 Bucket Name created by S3 Blueprint"
      EBSSize:
        default: "EBS Volume Size"
      EBSType:
        default: "EBS Volume Type"
      EBSIOPS:
        default: "EBS Iops"
      DesiredCapacity: 
        default: "Desired Capacity ASG"
      InstanceCountMin: 
        default: "Minimum Instance Count ASG"
      InstanceCountMax: 
        default: "Maximum Instance Count ASG"
      SnsTopicArn: 
        default: "SNS Topic ARN"
      LBTargetGroupArn:
        default: AutoScaling Group ALB or NLB Target Group ARN
      InstanceProfileName:
        default: "Instance Profile Name"
      InstanceType:
        default: "Instance Type"

Parameters:
  # ASG Internal Parameters
  NodeName:
    Type: String
    Description: Unique application name.
  
  EBSSize:
    Description: Size of root EBS volume
    Default: 50
    Type: Number
  
  EBSType:
    Description: EBS Volume Type.
    Default: gp3
    Type: String
    AllowedValues: [gp2,gp3,io1,io2,sc1,st1,standard]

  EBSIOPS:
    Type: Number
    Description: "[Required only for gp3 (default 3,000), io1 and io2 volumes]. This parameter is not applicable for other EBS volume types (sc1, st1, standard), please leave it as the default number if that is the case. "
    Default: 3000
  
  InstanceProfileName:
    Description: The instance profile name for EC2. Standard L2 BP Instance Profile for the tenants (if pre-created !!!). if not provided, a new profile will be created with minimum permessions to read from ConfigureStore bucket and read a sample secret stored in secrets manager.
    Type: String

  InstanceType:
    Description: Any valid EC2 instance size is allowed.
    Default: t3.micro
    Type: String
   
  SecurityGroups:
    Description: Existing security groups to associate with instance (optional)
    Type: String
    AllowedPattern: ^$|^(sg-[a-z0-9]+,?)+$

  OsType:
    Description: Operating system, Windows or Linux
    Default: linux
    Type: String
    AllowedValues: [ windows, linux ]
  
  DesiredCapacity:
    Description: Required. Max Cluster Size. The maximum number of instances to scale up to based on policies
    Default: '3'
    Type: String

  InstanceCountMin:
    Description: Required. The minimum number of instances to scale down to based on policies
    Default: '2'
    Type: String
    
  InstanceCountMax:
    Description: Required. Max Cluster Size. The maximum number of instances to scale up to based on policies
    Default: '9'
    Type: String

  LBTargetGroupArn:
    Description: Optional, ALB or NLB TargetGroup ARN (Do)
    Type: String
  
  # Blueprint App parameters
  SecurityZone:
    Default: ic
    Type: String
    Description: Security Zone for the Blueprint
    AllowedValues: [ic,mgmt,res,sec]
  
  DataClassification:
    Default: Confidential
    Type: String
    Description: Data Classification for the Blueprint
    AllowedValues: [GroupUse,Public,Confidential,CustomerPersonal,HighlyProtected]

  ConfigureStoreBucket:
    Description: Existing ConfigureStore S3 Bucket Name created by S3 Blueprint
    Type: String
  
  BluePrintTag:
    Default: ASG-Internal-Blueprint
    Type: String

  AppPort:
    Description: Application tcp port. there is no support for UDP applications at the moment.
    Default: 443
    Type: Number

  AppSoe:
    Default: ""
    Type: String
    Description: Sampleapp SOE AMI to use. if not provided, latest windows or linux ami will be used
  
  UserdataS3script:
      Type: String
      Description: Please provide the script KeyName under S3 bucket e.g./abc/scripts.sh if the script under abc folder named as scripts.sh

  AppSecret:
    NoEcho: true # Values to be hidden
    Type: String
    Default: 'MySecretValue'

  LatestLinuxAmiId:
    Description: Latest CBA Approved Linux AMI Id
    Type: String

  LatestWindowsAmiId:
    Description: Latest CBA Approved Windows AMI Id
    Type: String

  SnsTopicArn:
    Type: String
    Description: Topic arn to receive notifications about autoscaling activities. if not provided, a new sns topic will be created

      # ## Custom Tag Parameters
  CustomTag1Name:
    Default: ""
    Type: String
    Description: Custom Tag Name for ASG
  CustomTag1Value:
    Default: ""
    Type: String
    Description: Custom Tag Value for ASG
  CustomTag2Name:
    Default: ""
    Type: String
    Description: Custom Tag Name for ASG
  CustomTag2Value:
    Default: ""
    Type: String
    Description: Custom Tag Value for ASG
  CustomTag3Name:
    Default: ""
    Type: String
    Description: Custom Tag Name for ASG
  CustomTag3Value:
    Default: ""
    Type: String
    Description: Custom Tag Value for ASG
  CustomTag4Name:
    Default: ""
    Type: String
    Description: Custom Tag Name for ASG
  CustomTag4Value:
    Default: ""
    Type: String
    Description: Custom Tag Value for ASG
  CustomTag5Name:
    Default: ""
    Type: String
    Description: Custom Tag Name for ASG
  CustomTag5Value:
    Default: ""
    Type: String
    Description: Custom Tag Value for ASG
  CustomTag6Name:
    Default: ""
    Type: String
    Description: Custom Tag Name for ASG
  CustomTag6Value:
    Default: ""
    Type: String
    Description: Custom Tag Value for ASG
  CustomTag7Name:
    Default: ""
    Type: String
    Description: Custom Tag Name for ASG
  CustomTag7Value:
    Default: ""
    Type: String
    Description: Custom Tag Value for ASG
  CustomTag8Name:
    Default: ""
    Type: String
    Description: Custom Tag Name for ASG
  CustomTag8Value:
    Default: ""
    Type: String
    Description: Custom Tag Value for ASG
  CustomTag9Name:
    Default: ""
    Type: String
    Description: Custom Tag Name for ASG
  CustomTag9Value:
    Default: ""
    Type: String
    Description: Custom Tag Value for ASG
  CustomTag10Name:
    Default: ""
    Type: String
    Description: Custom Tag Name for ASG
  CustomTag10Value:
    Default: ""
    Type: String
    Description: Custom Tag Value for ASG



#ASG internal consuming ASG.yml(ASG-Only) service catalog product
Resources:
  ASGInternalBlueprint:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: "BP-ASG-Product"
      ProvisioningArtifactName: "1.0.2"
      ProvisioningParameters:
        - Key: "NodeName"
          Value: !Ref NodeName
        - Key: "EBSSize"
          Value: !Ref EBSSize
        - Key: "EBSType"
          Value: !Ref EBSType
        - Key: "EBSIOPS"
          Value: !Ref EBSIOPS
        - Key: "InstanceProfileName"
          Value: !Ref InstanceProfileName
        - Key: "InstanceType"
          Value: !Ref InstanceType
        - Key: "SecurityGroups"
          Value: !Ref SecurityGroups
        - Key: "OsType"
          Value: !Ref OsType
        - Key: "DesiredCapacity"
          Value: !Ref DesiredCapacity
        - Key: "InstanceCountMin"
          Value: !Ref InstanceCountMin
        - Key: "InstanceCountMax"
          Value: !Ref InstanceCountMax
        - Key: "LBTargetGroupArn"
          Value: !Ref LBTargetGroupArn
        - Key: "SecurityZone"
          Value: !Ref SecurityZone
        - Key: "DataClassification"
          Value: !Ref DataClassification
        - Key: "ConfigureStoreBucket"
          Value: !Ref ConfigureStoreBucket
        - Key: "UserdataS3script"
          Value: !Ref UserdataS3script
        - Key: "BluePrintTag"
          Value: !Ref BluePrintTag
        - Key: "AppPort"
          Value: !Ref AppPort
        - Key: "AppSoe"
          Value: !Ref AppSoe
        - Key: "AppSecret"
          Value: !Ref AppSecret
        - Key: "LatestLinuxAmiId"
          Value: !Ref LatestLinuxAmiId
        - Key: "LatestWindowsAmiId"
          Value: !Ref LatestWindowsAmiId
        - Key: "SnsTopicArn"
          Value: !Ref SnsTopicArn
        - Key: "CustomTag1Name"
          Value: !Ref CustomTag1Name
        - Key: "CustomTag1Value"
          Value: !Ref CustomTag1Value
        - Key: "CustomTag2Name"
          Value: !Ref CustomTag2Name
        - Key: "CustomTag2Value"
          Value: !Ref CustomTag2Value
        - Key: "CustomTag3Name"
          Value: !Ref CustomTag3Name
        - Key: "CustomTag3Value"
          Value: !Ref CustomTag3Value
        - Key: "CustomTag4Name"
          Value: !Ref CustomTag4Name
        - Key: "CustomTag4Value"
          Value: !Ref CustomTag4Value
        - Key: "CustomTag5Name"
          Value: !Ref CustomTag5Name
        - Key: "CustomTag5Value"
          Value: !Ref CustomTag5Value
        - Key: "CustomTag6Name"
          Value: !Ref CustomTag6Name
        - Key: "CustomTag6Value"
          Value: !Ref CustomTag6Value
        - Key: "CustomTag7Name"
          Value: !Ref CustomTag7Name
        - Key: "CustomTag7Value"
          Value: !Ref CustomTag7Value
        - Key: "CustomTag8Name"
          Value: !Ref CustomTag8Name
        - Key: "CustomTag8Value"
          Value: !Ref CustomTag8Value
        - Key: "CustomTag9Name"
          Value: !Ref CustomTag9Name
        - Key: "CustomTag9Value"
          Value: !Ref CustomTag9Value
        - Key: "CustomTag10Name"
          Value: !Ref CustomTag10Name
        - Key: "CustomTag10Value"
          Value: !Ref CustomTag10Value

Outputs:
  AppSgName:
    Description: App security Group Name
    Value: !GetAtt ASGInternalBlueprint.Outputs.AppSgName
  AutoScalingGroupName:
    Description: Autoscaling group Name 
    Value: !GetAtt ASGInternalBlueprint.Outputs.AutoScalingGroupName
  EC2InstanceProfileName:
    Description: EC2InstanceProfile Name
    Value: !GetAtt ASGInternalBlueprint.Outputs.EC2InstanceProfileName
  InstanceProfileSsmParameterPath:
    Description: EC2 Instance Profile SSM Parameter Path
    Value: !GetAtt ASGInternalBlueprint.Outputs.InstanceProfileSsmParameterPath
  AppSecretSecretsManagerARN:
    Description: Application Secret AWS Secrets Manager
    Value: !GetAtt ASGInternalBlueprint.Outputs.AppSecretSecretsManagerARN
  AppSecretSSMParameterPath:
    Description: Application Secret SSM Parameter Path
    Value: !GetAtt ASGInternalBlueprint.Outputs.AppSecretSSMParameterPath
  LaunchTemplateName:
    Description: Launch Template Name 
    Value: !GetAtt ASGInternalBlueprint.Outputs.LaunchTemplateName
  SNSTopicArnName:
    Description: SNS topic ARN
    Value: !GetAtt ASGInternalBlueprint.Outputs.SNSTopicArnName
  SNSTopicSSMParameterPath:
    Description: SNS Topic SSM Parameter Path
    Value: !GetAtt ASGInternalBlueprint.Outputs.SNSTopicSSMParameterPath
